nodeLinker: node-modules

enableGlobalCache: true

compressionLevel: mixed

defaultSemverRangePrefix: "^"

packageExtensions:
  "react-native@*":
    peerDependencies:
      "@babel/core": "*"
      "@babel/preset-env": "*"