name: EAS Build

on:
  push:
    branches: [main, master]
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      platform:
        description: 'Platform to build for'
        required: true
        type: choice
        options:
          - ios
          - android
          - all

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          expo-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
          
      - name: Build on EAS
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            PLATFORM="${{ github.event.inputs.platform }}"
          else
            PLATFORM="all"
          fi
          
          if [ "$PLATFORM" == "all" ]; then
            eas build --platform ios --non-interactive
            eas build --platform android --non-interactive
          else
            eas build --platform $PLATFORM --non-interactive
          fi